/*
 * Copyright 2022 ABSA Group Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package za.co.absa.pramen.core.samples

import java.sql.{Connection, SQLException}

trait RdbExampleTable {
  val tableName: String
  val ddl: String
  val comments: Seq[String]
  val inserts: Seq[String]

  @throws[SQLException]
  def initTable(connection: Connection): Unit = {
    val statement = connection.createStatement

    statement.execute(ddl)
    connection.commit()

    comments.foreach(sql => statement.executeUpdate(sql))
    connection.commit()

    inserts.foreach(sql => statement.executeUpdate(sql))
    connection.commit()
  }

  @throws[SQLException]
  def dropTable(connection: Connection): Unit = {
    val statement = connection.createStatement
    try {
      statement.executeUpdate(s"DROP TABLE $tableName")
      connection.commit()
    } finally {
      if (statement != null) statement.close()
    }
  }
}

object RdbExampleTable {
  object Company extends RdbExampleTable {
    val tableName: String = "COMPANY"
    val schemaName: String = "PUBLIC"
    val databaseName: String = "PUBLIC"

    val ddl: String =
      s"""
         |CREATE TABLE $tableName (
         |  id INT NOT NULL,
         |  name VARCHAR(50) NOT NULL,
         |  description VARCHAR NOT NULL,
         |  email VARCHAR(50) NOT NULL,
         |  founded DATE NOT NULL,
         |  is_tax_free BOOLEAN,
         |  tax_id BIGINT,
         |  last_updated TIMESTAMP NOT NULL,
         |  info_date VARCHAR(10) NOT NULL,
         |  PRIMARY KEY (id))
         |""".stripMargin

    val comments: Seq[String] = Seq(
      s"COMMENT ON COLUMN $tableName.id IS 'This is the record id'",
      s"COMMENT ON COLUMN $tableName.name IS 'This is company name'"
    )

    val inserts: Seq[String] = Seq(
      s"INSERT INTO $tableName VALUES (1,'Company1', 'description1', 'company1@example.com', DATE '2000-10-11', FALSE, 123, TIMESTAMP '2020-11-04 10:11:00+02:00', '2022-02-18')",
      s"INSERT INTO $tableName VALUES (2,'Company2', 'description2', 'company2@example.com', DATE '2005-03-29', TRUE, 456, TIMESTAMP '2020-11-04 10:22:33+02:00', '2022-02-18')",
      s"INSERT INTO $tableName VALUES (3,'Company3', 'description3', 'company3@example.com', DATE '2016-12-30', FALSE, NULL, TIMESTAMP '2020-11-04 10:33:59+02:00', '2022-02-18')",
      s"INSERT INTO $tableName VALUES (4,'Company4', 'description4', 'company4@example.com', DATE '2016-12-31', NULL, NULL, TIMESTAMP '2020-11-04 10:34:22+02:00', '2022-02-19')"
    )
  }

  object IncrementalTable extends RdbExampleTable {
    val tableName: String = "INCREMENTAL_TABLE"
    val schemaName: String = "PUBLIC"
    val databaseName: String = "PUBLIC"

    val ddl: String =
      s"""
         |CREATE TABLE $tableName (
         |  id INT NOT NULL,
         |  name VARCHAR(50) NOT NULL,
         |  last_updated TIMESTAMP NOT NULL,
         |  info_date VARCHAR(10) NOT NULL,
         |  PRIMARY KEY (id))
         |""".stripMargin

    override val comments: Seq[String] = Seq.empty

    val inserts: Seq[String] = Seq(
      s"INSERT INTO $tableName VALUES (1,'John', TIMESTAMP '2022-02-18 10:11:00', '2022-02-18')",
      s"INSERT INTO $tableName VALUES (2,'Jack', TIMESTAMP '2022-02-18 10:22:33', '2022-02-18')",
      s"INSERT INTO $tableName VALUES (3,'Jill', TIMESTAMP '2022-02-18 10:33:59', '2022-02-18')"
    )

    val inserts2: Seq[String] = Seq(
      s"INSERT INTO $tableName VALUES (4,'Mary', TIMESTAMP '2022-02-18 11:11:00', '2022-02-18')",
      s"INSERT INTO $tableName VALUES (5,'Jane', TIMESTAMP '2022-02-18 11:22:33', '2022-02-18')",
      s"INSERT INTO $tableName VALUES (6,'Kate', TIMESTAMP '2022-02-18 11:33:59', '2022-02-18')"
    )
  }

  object Arrays extends RdbExampleTable {
    val tableName: String = "ARRAYS"
    val schemaName: String = "PUBLIC"
    val databaseName: String = "PUBLIC"

    val ddl: String =
      s"""CREATE TABLE $tableName (
         |    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         |    str_array VARCHAR(255) ARRAY,
         |    bool_array BOOLEAN ARRAY,
         |    short_array SMALLINT ARRAY,
         |    int_array INTEGER ARRAY,
         |    long_array BIGINT ARRAY,
         |    dec_array DECIMAL(10,2) ARRAY,
         |    date_array DATE ARRAY,
         |    ts_array TIMESTAMP ARRAY,
         |    bin_array VARBINARY(255) ARRAY
         |)
         |""".stripMargin

    val comments: Seq[String] = Seq(
      s"COMMENT ON COLUMN $tableName.id IS 'This is the record id'",
      s"COMMENT ON COLUMN $tableName.bool_array IS 'This a flags array'"
    )

    val inserts: Seq[String] = Seq(
      s"""INSERT INTO $tableName (
        |    str_array, bool_array, short_array, int_array, long_array,
        |    dec_array, date_array, ts_array, bin_array
        |)
        |VALUES (
        |    ARRAY['String1','String2'],
        |    ARRAY[TRUE, FALSE, TRUE],
        |    ARRAY[10, 20, 30],
        |    ARRAY[100, 200, 300],
        |    ARRAY[10000000000, 20000000000],
        |    ARRAY[123.45, 678.90],
        |    ARRAY[DATE '2025-01-01', DATE '2025-12-31'],
        |    ARRAY[TIMESTAMP '2025-01-01 10:00:00', TIMESTAMP '2025-06-01 12:30:00'],
        |    ARRAY[X'DEADBEEF', X'010203']
        |);""".stripMargin,
      s"""INSERT INTO $tableName (
         |    str_array, bool_array, short_array, int_array, long_array,
         |    dec_array, date_array, ts_array, bin_array
         |)
         |VALUES (
         |    ARRAY['String3',null],
         |    ARRAY[TRUE, null, TRUE],
         |    ARRAY[50, null],
         |    ARRAY[null, 200, 300],
         |    ARRAY[21234540000, null],
         |    ARRAY[null, 678.90],
         |    ARRAY[DATE '2025-01-01', null],
         |    ARRAY[null, TIMESTAMP '2025-06-01 12:30:00'],
         |    ARRAY[X'01ABCD23', null]
         |);""".stripMargin,
      s"""INSERT INTO $tableName (
         |    str_array, bool_array, short_array, int_array, long_array,
         |    dec_array, date_array, ts_array, bin_array
         |)
         |VALUES (
         |    null, null, null, null, null,
         |    null, null, null, null
         |);""".stripMargin
    )
  }

  object Empty extends RdbExampleTable {
    val tableName: String = "empty"

    val ddl: String =
      s"""
         |CREATE TABLE $tableName (
         |  id INT NOT NULL,
         |  PRIMARY KEY (id))
         |""".stripMargin

    val comments = Seq.empty[String]

    val inserts = Seq.empty[String]
  }

}
