#
# Copyright 2022 ABSA Group Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: JaCoCo

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: jacoco-report-${{ github.ref }}
  cancel-in-progress: true

env:
  SCALA_VERSION: 2.12.20
  SPARK_VERSION: 3.4.4

  # hint: "group thresholds" are in format: 'overall*changed-files-average*per-changed-file'
  REPORT_GROUPS: |
    - name: pramen-core
      paths:
        - 'pramen/core/target/**/jacoco-report/jacoco.xml'
      thresholds: '70*90*60'
    - name: pramen-extras
      paths:
        - 'pramen/extras/target/**/jacoco-report/jacoco.xml'
      thresholds: '57*80*60'

jobs:
  detect:
    name: Detect Changed Files
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    outputs:
      scala_changed: ${{ steps.filter.outputs.scala }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          token: ""
          filters: |
            scala:
              - 'pramen/**/*.scala'
              - 'pramen/*/src/**'
              - 'pramen/build.sbt'
              - 'pramen/project/**'
              - 'pramen/jmf-rules.txt'
              - '.github/workflows/jacoco.yml'

  jacoco-report:
    name: JaCoCo Report
    needs: detect
    if: needs.detect.outputs.scala_changed == 'true'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: 8
          cache: sbt

      - name: Build and run tests with coverage
        working-directory: ./pramen
        run: sbt -DSPARK_VERSION=${{ env.SPARK_VERSION }} ++${{ env.SCALA_VERSION }} jacoco

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'

      - name: Add JaCoCo Report in PR comments
        uses: MoranaApps/jacoco-report@3575c005e31adda0bf6868b69d48a0114e912845 # v3.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          global-thresholds: '70*80'
          report-thresholds-default: '57*80*60'
          skip-unchanged: 'true'
          evaluate-unchanged: 'true'
          report-groups: ${{ env.REPORT_GROUPS }}

  noop:
    name: No Operation
    needs: detect
    if: needs.detect.outputs.scala_changed != 'true'
    runs-on: ubuntu-22.04
    steps:
      - run: echo "No changes in Scala related files — passing."
